language: php

php:
  - 5.4
  - 5.5

install:
  - sudo apt-get install curl libcurl3 libcurl3-dev
  - echo "extension=php_curl.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install

secure: "XV4apZjig8YWL/0scUDAJZn2i74bnWILh2oVMJj2o2rMZjaW0tWI/44dzt27OiyPn22w0D/Id5Ba2k7UBrjPyW+pMKbq5H5X95nbfuLJyGytIIxIfYIzkWq/7Ny42nTvKrp+XJB4tYItCPIlXuB9IW/OVmWbuKGqO5w/NZQD8ig="

script:
  - cd tests && ../vendor/bin/codecept run crwl AdsQueryCest.php --debug  # self tests